In [1]:
import utils
import networkx as nx
import numpy as np
import branch_helpers as helpers

In [2]:
rando = utils.random_graph(5)
rando_mat = nx.to_numpy_matrix(rando)
print(rando_mat)


[[0.         0.38747599 0.30241003 0.66738619 0.39737557]
 [0.38747599 0.         0.28826991 0.28527361 0.67759525]
 [0.30241003 0.28826991 0.         0.54554554 0.69525316]
 [0.66738619 0.28527361 0.54554554 0.         0.90114226]
 [0.39737557 0.67759525 0.69525316 0.90114226 0.        ]]


In [3]:
#print(rando_mat)
#nx.draw(rando)
infinitized_matrix = helpers.make_diag_infinite(rando_mat)
reduced_matrix, cost = helpers.reduce_matrix(infinitized_matrix)
mat = np.array([[0.0, 20, 30, 10, 11], [15, 0.0, 16, 4, 2], [3, 5, 0.0, 2, 4], [19, 6, 18, 0.0, 3], [16, 4, 7, 16, 0.0]])
#infin = helpers.make_diag_infinite(mat)
#red2, cost2 = helpers.reduce_matrix(infin)

#print(cost2)
#print(red2)

print(cost)
print(reduced_matrix)




1.6535682627393506
[[       inf 0.08506596 0.         0.36497615 0.        ]
 [0.10220238        inf 0.0029963  0.         0.2973561 ]
 [0.01414012 0.                inf 0.25727563 0.31201771]
 [0.38211258 0.         0.26027193        inf 0.52090311]
 [0.         0.28021968 0.29787759 0.50376669        inf]]


In [4]:
graph_size = 5
rando = utils.random_graph(graph_size)
rando_mat = nx.to_numpy_matrix(rando)
infinitized_matrix = helpers.make_diag_infinite(rando_mat)
reduced_matrix, cost = helpers.reduce_matrix(infinitized_matrix)

tree = helpers.Tree(None, list(range(graph_size)))
zero_node = helpers.Path_node(None, [], 0, reduced_matrix, tree, cost)
print(zero_node)



parent: None
children: []
graph_node: 0
adj mat: 
[[       inf 0.         0.11813327 0.         0.16824551]
 [0.04148026        inf 0.         0.14364614 0.        ]
 [0.15961352 0.                inf 0.04148026 0.11856956]
 [0.         0.10216589 0.                inf 0.30051996]
 [0.20972577 0.         0.11856956 0.34200022        inf]]
cost: 1.7773885556425986
remaining graph nodes: [1, 2, 3, 4]
